// Code generated by "stringer -type=AuditOutcome -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuditOutcomeSuccess-1]
	_ = x[AuditOutcomeFailure-2]
}

const _AuditOutcome_name = "successfailure"

var _AuditOutcome_index = [...]uint8{0, 7, 14}

func (i AuditOutcome) String() string {
	i -= 1
	if i < 0 || i >= AuditOutcome(len(_AuditOutcome_index)-1) {
		return "AuditOutcome(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AuditOutcome_name[_AuditOutcome_index[i]:_AuditOutcome_index[i+1]]
}
