// Code generated by "stringer -type=AuditActorType -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuditActorTypeUser-1]
	_ = x[AuditActorTypeServiceAccount-2]
}

const _AuditActorType_name = "UserServiceAccount"

var _AuditActorType_index = [...]uint8{0, 4, 18}

func (i AuditActorType) String() string {
	i -= 1
	if i < 0 || i >= AuditActorType(len(_AuditActorType_index)-1) {
		return "AuditActorType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AuditActorType_name[_AuditActorType_index[i]:_AuditActorType_index[i+1]]
}
