// Code generated by "stringer -type=DomainCertStatus -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DomainCertStatusNone-0]
	_ = x[DomainCertStatusPendingCreate-1]
	_ = x[DomainCertStatusCreated-2]
	_ = x[DomainCertStatusPendingDelete-3]
}

const _DomainCertStatus_name = "nonependingCreatecreatedpendingDelete"

var _DomainCertStatus_index = [...]uint8{0, 4, 17, 24, 37}

func (i DomainCertStatus) String() string {
	if i < 0 || i >= DomainCertStatus(len(_DomainCertStatus_index)-1) {
		return "DomainCertStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DomainCertStatus_name[_DomainCertStatus_index[i]:_DomainCertStatus_index[i+1]]
}
