// Code generated by "stringer -type=NotificationChannelType -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotificationChannelTypeWebhook-1]
	_ = x[NotificationChannelTypeDiscord-2]
	_ = x[NotificationChannelTypePull-3]
}

const _NotificationChannelType_name = "webhookdiscordpull"

var _NotificationChannelType_index = [...]uint8{0, 7, 14, 18}

func (i NotificationChannelType) String() string {
	i -= 1
	if i < 0 || i >= NotificationChannelType(len(_NotificationChannelType_index)-1) {
		return "NotificationChannelType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _NotificationChannelType_name[_NotificationChannelType_index[i]:_NotificationChannelType_index[i+1]]
}
