// Code generated by "stringer -type=TransformPhase -linecomment -output transformphase_string.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransformPhaseRequest-0]
	_ = x[TransformPhaseResponse-1]
}

const _TransformPhase_name = "requestresponse"

var _TransformPhase_index = [...]uint8{0, 7, 15}

func (i TransformPhase) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TransformPhase_index)-1 {
		return "TransformPhase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransformPhase_name[_TransformPhase_index[idx]:_TransformPhase_index[idx+1]]
}
