// Code generated by "stringer -type=WAFAction -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WAFActionLog-0]
	_ = x[WAFActionAllow-1]
	_ = x[WAFActionBlock-2]
}

const _WAFAction_name = "logallowblock"

var _WAFAction_index = [...]uint8{0, 3, 8, 13}

func (i WAFAction) String() string {
	if i < 0 || i >= WAFAction(len(_WAFAction_index)-1) {
		return "WAFAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WAFAction_name[_WAFAction_index[i]:_WAFAction_index[i+1]]
}
